/**
 * Download token helpers.
 *
 * Each (user × product) purchase gets one Download row with an opaque token.
 * The token is the only secret needed to stream the file — no session required
 * so tokens can be embedded in emails safely.
 */
import { db }                                            from '@/lib/db'
import { DOWNLOAD_TTL_HOURS, DOWNLOAD_MAX_REGENERATIONS } from '@/lib/s3'
import type { Download }                                  from '@prisma/client'

// ─── Create ───────────────────────────────────────────────────────────────────

/**
 * Create a Download record for one (user, purchase, product) triple.
 * The token is auto-generated by Prisma (@default(cuid())).
 */
export async function createDownloadToken(
  userId:     string,
  purchaseId: string,
  productId:  string,
): Promise<Download> {
  const expiresAt = new Date(
    Date.now() + DOWNLOAD_TTL_HOURS * 60 * 60 * 1000
  )

  return db.download.create({
    data: {
      userId,
      purchaseId,
      productId,
      expiresAt,
      maxDownloads: DOWNLOAD_MAX_REGENERATIONS,
    },
  })
}

// ─── URL builder ──────────────────────────────────────────────────────────────

/** Full URL a buyer uses to stream / download their file. */
export function buildDownloadLink(token: string): string {
  const base = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000'
  return `${base}/api/downloads/${token}`
}
